# Generated by Django 4.0.4 on 2022-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banck_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Фамилия Имя')),
                ('balanc', models.BigIntegerField(default=10000, verbose_name='Баланс')),
                ('pin', models.IntegerField(max_length=4, verbose_name='Секретный Пин')),
            ],
        ),
    ]
